<?php
/**
 * ProductGroupItemApi
 * PHP version 7.3
 *
 * @category Class
 * @package  Vilo\ProductService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Product Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Vilo\ProductService\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Vilo\ProductService\ApiException;
use Vilo\ProductService\Configuration;
use Vilo\ProductService\HeaderSelector;
use Vilo\ProductService\ObjectSerializer;

/**
 * ProductGroupItemApi Class Doc Comment
 *
 * @category Class
 * @package  Vilo\ProductService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductGroupItemApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation deleteProductGroupItemItem
     *
     * Removes the ProductGroupItem resource.
     *
     * @param  string $id Resource identifier (required)
     *
     * @throws \Vilo\ProductService\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteProductGroupItemItem($id)
    {
        $this->deleteProductGroupItemItemWithHttpInfo($id);
    }

    /**
     * Operation deleteProductGroupItemItemWithHttpInfo
     *
     * Removes the ProductGroupItem resource.
     *
     * @param  string $id Resource identifier (required)
     *
     * @throws \Vilo\ProductService\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteProductGroupItemItemWithHttpInfo($id)
    {
        $request = $this->deleteProductGroupItemItemRequest($id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation deleteProductGroupItemItemAsync
     *
     * Removes the ProductGroupItem resource.
     *
     * @param  string $id Resource identifier (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteProductGroupItemItemAsync($id)
    {
        return $this->deleteProductGroupItemItemAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteProductGroupItemItemAsyncWithHttpInfo
     *
     * Removes the ProductGroupItem resource.
     *
     * @param  string $id Resource identifier (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteProductGroupItemItemAsyncWithHttpInfo($id)
    {
        $returnType = '';
        $request = $this->deleteProductGroupItemItemRequest($id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteProductGroupItemItem'
     *
     * @param  string $id Resource identifier (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteProductGroupItemItemRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling deleteProductGroupItemItem'
            );
        }

        $resourcePath = '/product_group_items/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getProductGroupItemCollection
     *
     * Retrieves the collection of ProductGroupItem resources.
     *
     * @param  int $page The collection page number (optional, default to 1)
     * @param  int $items_per_page The number of items per page (optional, default to 30)
     * @param  string $order_sequence order_sequence (optional)
     * @param  string $fk_product fk_product (optional)
     * @param  string[] $fk_product2 fk_product2 (optional)
     * @param  string $fk_product_group fk_product_group (optional)
     * @param  string[] $fk_product_group2 fk_product_group2 (optional)
     *
     * @throws \Vilo\ProductService\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Vilo\ProductService\Model\InlineResponse2001
     */
    public function getProductGroupItemCollection($page = 1, $items_per_page = 30, $order_sequence = null, $fk_product = null, $fk_product2 = null, $fk_product_group = null, $fk_product_group2 = null)
    {
        list($response) = $this->getProductGroupItemCollectionWithHttpInfo($page, $items_per_page, $order_sequence, $fk_product, $fk_product2, $fk_product_group, $fk_product_group2);
        return $response;
    }

    /**
     * Operation getProductGroupItemCollectionWithHttpInfo
     *
     * Retrieves the collection of ProductGroupItem resources.
     *
     * @param  int $page The collection page number (optional, default to 1)
     * @param  int $items_per_page The number of items per page (optional, default to 30)
     * @param  string $order_sequence (optional)
     * @param  string $fk_product (optional)
     * @param  string[] $fk_product2 (optional)
     * @param  string $fk_product_group (optional)
     * @param  string[] $fk_product_group2 (optional)
     *
     * @throws \Vilo\ProductService\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Vilo\ProductService\Model\InlineResponse2001, HTTP status code, HTTP response headers (array of strings)
     */
    public function getProductGroupItemCollectionWithHttpInfo($page = 1, $items_per_page = 30, $order_sequence = null, $fk_product = null, $fk_product2 = null, $fk_product_group = null, $fk_product_group2 = null)
    {
        $request = $this->getProductGroupItemCollectionRequest($page, $items_per_page, $order_sequence, $fk_product, $fk_product2, $fk_product_group, $fk_product_group2);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Vilo\ProductService\Model\InlineResponse2001' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Vilo\ProductService\Model\InlineResponse2001', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Vilo\ProductService\Model\InlineResponse2001';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Vilo\ProductService\Model\InlineResponse2001',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getProductGroupItemCollectionAsync
     *
     * Retrieves the collection of ProductGroupItem resources.
     *
     * @param  int $page The collection page number (optional, default to 1)
     * @param  int $items_per_page The number of items per page (optional, default to 30)
     * @param  string $order_sequence (optional)
     * @param  string $fk_product (optional)
     * @param  string[] $fk_product2 (optional)
     * @param  string $fk_product_group (optional)
     * @param  string[] $fk_product_group2 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProductGroupItemCollectionAsync($page = 1, $items_per_page = 30, $order_sequence = null, $fk_product = null, $fk_product2 = null, $fk_product_group = null, $fk_product_group2 = null)
    {
        return $this->getProductGroupItemCollectionAsyncWithHttpInfo($page, $items_per_page, $order_sequence, $fk_product, $fk_product2, $fk_product_group, $fk_product_group2)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getProductGroupItemCollectionAsyncWithHttpInfo
     *
     * Retrieves the collection of ProductGroupItem resources.
     *
     * @param  int $page The collection page number (optional, default to 1)
     * @param  int $items_per_page The number of items per page (optional, default to 30)
     * @param  string $order_sequence (optional)
     * @param  string $fk_product (optional)
     * @param  string[] $fk_product2 (optional)
     * @param  string $fk_product_group (optional)
     * @param  string[] $fk_product_group2 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProductGroupItemCollectionAsyncWithHttpInfo($page = 1, $items_per_page = 30, $order_sequence = null, $fk_product = null, $fk_product2 = null, $fk_product_group = null, $fk_product_group2 = null)
    {
        $returnType = '\Vilo\ProductService\Model\InlineResponse2001';
        $request = $this->getProductGroupItemCollectionRequest($page, $items_per_page, $order_sequence, $fk_product, $fk_product2, $fk_product_group, $fk_product_group2);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getProductGroupItemCollection'
     *
     * @param  int $page The collection page number (optional, default to 1)
     * @param  int $items_per_page The number of items per page (optional, default to 30)
     * @param  string $order_sequence (optional)
     * @param  string $fk_product (optional)
     * @param  string[] $fk_product2 (optional)
     * @param  string $fk_product_group (optional)
     * @param  string[] $fk_product_group2 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getProductGroupItemCollectionRequest($page = 1, $items_per_page = 30, $order_sequence = null, $fk_product = null, $fk_product2 = null, $fk_product_group = null, $fk_product_group2 = null)
    {
        if ($items_per_page !== null && $items_per_page < 0) {
            throw new \InvalidArgumentException('invalid value for "$items_per_page" when calling ProductGroupItemApi.getProductGroupItemCollection, must be bigger than or equal to 0.');
        }


        $resourcePath = '/product_group_items';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if (is_array($page)) {
            $page = ObjectSerializer::serializeCollection($page, 'form', true);
        }
        if ($page !== null) {
            $queryParams['page'] = $page;
        }
        // query params
        if (is_array($items_per_page)) {
            $items_per_page = ObjectSerializer::serializeCollection($items_per_page, 'form', true);
        }
        if ($items_per_page !== null) {
            $queryParams['itemsPerPage'] = $items_per_page;
        }
        // query params
        if (is_array($order_sequence)) {
            $order_sequence = ObjectSerializer::serializeCollection($order_sequence, 'form', true);
        }
        if ($order_sequence !== null) {
            $queryParams['order[sequence]'] = $order_sequence;
        }
        // query params
        if (is_array($fk_product)) {
            $fk_product = ObjectSerializer::serializeCollection($fk_product, 'form', true);
        }
        if ($fk_product !== null) {
            $queryParams['fkProduct'] = $fk_product;
        }
        // query params
        if ($fk_product2 !== null) {
            if('form' === 'form' && is_array($fk_product2)) {
                foreach($fk_product2 as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['fkProduct[]'] = $fk_product2;
            }
        }
        // query params
        if (is_array($fk_product_group)) {
            $fk_product_group = ObjectSerializer::serializeCollection($fk_product_group, 'form', true);
        }
        if ($fk_product_group !== null) {
            $queryParams['fkProductGroup'] = $fk_product_group;
        }
        // query params
        if ($fk_product_group2 !== null) {
            if('form' === 'form' && is_array($fk_product_group2)) {
                foreach($fk_product_group2 as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['fkProductGroup[]'] = $fk_product_group2;
            }
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/ld+json', 'text/csv', 'text/html']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/ld+json', 'text/csv', 'text/html'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getProductGroupItemItem
     *
     * Retrieves a ProductGroupItem resource.
     *
     * @param  string $id Resource identifier (required)
     *
     * @throws \Vilo\ProductService\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead
     */
    public function getProductGroupItemItem($id)
    {
        list($response) = $this->getProductGroupItemItemWithHttpInfo($id);
        return $response;
    }

    /**
     * Operation getProductGroupItemItemWithHttpInfo
     *
     * Retrieves a ProductGroupItem resource.
     *
     * @param  string $id Resource identifier (required)
     *
     * @throws \Vilo\ProductService\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead, HTTP status code, HTTP response headers (array of strings)
     */
    public function getProductGroupItemItemWithHttpInfo($id)
    {
        $request = $this->getProductGroupItemItemRequest($id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getProductGroupItemItemAsync
     *
     * Retrieves a ProductGroupItem resource.
     *
     * @param  string $id Resource identifier (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProductGroupItemItemAsync($id)
    {
        return $this->getProductGroupItemItemAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getProductGroupItemItemAsyncWithHttpInfo
     *
     * Retrieves a ProductGroupItem resource.
     *
     * @param  string $id Resource identifier (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProductGroupItemItemAsyncWithHttpInfo($id)
    {
        $returnType = '\Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead';
        $request = $this->getProductGroupItemItemRequest($id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getProductGroupItemItem'
     *
     * @param  string $id Resource identifier (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getProductGroupItemItemRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getProductGroupItemItem'
            );
        }

        $resourcePath = '/product_group_items/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/ld+json', 'text/csv', 'text/html']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/ld+json', 'text/csv', 'text/html'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation patchProductGroupItemItem
     *
     * Updates the ProductGroupItem resource.
     *
     * @param  string $id Resource identifier (required)
     * @param  \Vilo\ProductService\Model\ProductGroupItem $product_group_item The updated ProductGroupItem resource (required)
     *
     * @throws \Vilo\ProductService\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead
     */
    public function patchProductGroupItemItem($id, $product_group_item)
    {
        list($response) = $this->patchProductGroupItemItemWithHttpInfo($id, $product_group_item);
        return $response;
    }

    /**
     * Operation patchProductGroupItemItemWithHttpInfo
     *
     * Updates the ProductGroupItem resource.
     *
     * @param  string $id Resource identifier (required)
     * @param  \Vilo\ProductService\Model\ProductGroupItem $product_group_item The updated ProductGroupItem resource (required)
     *
     * @throws \Vilo\ProductService\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead, HTTP status code, HTTP response headers (array of strings)
     */
    public function patchProductGroupItemItemWithHttpInfo($id, $product_group_item)
    {
        $request = $this->patchProductGroupItemItemRequest($id, $product_group_item);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation patchProductGroupItemItemAsync
     *
     * Updates the ProductGroupItem resource.
     *
     * @param  string $id Resource identifier (required)
     * @param  \Vilo\ProductService\Model\ProductGroupItem $product_group_item The updated ProductGroupItem resource (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchProductGroupItemItemAsync($id, $product_group_item)
    {
        return $this->patchProductGroupItemItemAsyncWithHttpInfo($id, $product_group_item)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation patchProductGroupItemItemAsyncWithHttpInfo
     *
     * Updates the ProductGroupItem resource.
     *
     * @param  string $id Resource identifier (required)
     * @param  \Vilo\ProductService\Model\ProductGroupItem $product_group_item The updated ProductGroupItem resource (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchProductGroupItemItemAsyncWithHttpInfo($id, $product_group_item)
    {
        $returnType = '\Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead';
        $request = $this->patchProductGroupItemItemRequest($id, $product_group_item);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'patchProductGroupItemItem'
     *
     * @param  string $id Resource identifier (required)
     * @param  \Vilo\ProductService\Model\ProductGroupItem $product_group_item The updated ProductGroupItem resource (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function patchProductGroupItemItemRequest($id, $product_group_item)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling patchProductGroupItemItem'
            );
        }
        // verify the required parameter 'product_group_item' is set
        if ($product_group_item === null || (is_array($product_group_item) && count($product_group_item) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $product_group_item when calling patchProductGroupItemItem'
            );
        }

        $resourcePath = '/product_group_items/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/ld+json', 'text/csv', 'text/html']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/ld+json', 'text/csv', 'text/html'],
                ['application/merge-patch+json']
            );
        }

        // for model (json/xml)
        if (isset($product_group_item)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($product_group_item));
            } else {
                $httpBody = $product_group_item;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PATCH',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postProductGroupItemCollection
     *
     * Creates a ProductGroupItem resource.
     *
     * @param  \Vilo\ProductService\Model\ProductGroupItemJsonld $product_group_item_jsonld The new ProductGroupItem resource (required)
     *
     * @throws \Vilo\ProductService\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead
     */
    public function postProductGroupItemCollection($product_group_item_jsonld)
    {
        list($response) = $this->postProductGroupItemCollectionWithHttpInfo($product_group_item_jsonld);
        return $response;
    }

    /**
     * Operation postProductGroupItemCollectionWithHttpInfo
     *
     * Creates a ProductGroupItem resource.
     *
     * @param  \Vilo\ProductService\Model\ProductGroupItemJsonld $product_group_item_jsonld The new ProductGroupItem resource (required)
     *
     * @throws \Vilo\ProductService\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead, HTTP status code, HTTP response headers (array of strings)
     */
    public function postProductGroupItemCollectionWithHttpInfo($product_group_item_jsonld)
    {
        $request = $this->postProductGroupItemCollectionRequest($product_group_item_jsonld);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 201:
                    if ('\Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation postProductGroupItemCollectionAsync
     *
     * Creates a ProductGroupItem resource.
     *
     * @param  \Vilo\ProductService\Model\ProductGroupItemJsonld $product_group_item_jsonld The new ProductGroupItem resource (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postProductGroupItemCollectionAsync($product_group_item_jsonld)
    {
        return $this->postProductGroupItemCollectionAsyncWithHttpInfo($product_group_item_jsonld)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postProductGroupItemCollectionAsyncWithHttpInfo
     *
     * Creates a ProductGroupItem resource.
     *
     * @param  \Vilo\ProductService\Model\ProductGroupItemJsonld $product_group_item_jsonld The new ProductGroupItem resource (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postProductGroupItemCollectionAsyncWithHttpInfo($product_group_item_jsonld)
    {
        $returnType = '\Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead';
        $request = $this->postProductGroupItemCollectionRequest($product_group_item_jsonld);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postProductGroupItemCollection'
     *
     * @param  \Vilo\ProductService\Model\ProductGroupItemJsonld $product_group_item_jsonld The new ProductGroupItem resource (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postProductGroupItemCollectionRequest($product_group_item_jsonld)
    {
        // verify the required parameter 'product_group_item_jsonld' is set
        if ($product_group_item_jsonld === null || (is_array($product_group_item_jsonld) && count($product_group_item_jsonld) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $product_group_item_jsonld when calling postProductGroupItemCollection'
            );
        }

        $resourcePath = '/product_group_items';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/ld+json', 'text/csv', 'text/html']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/ld+json', 'text/csv', 'text/html'],
                ['application/ld+json', 'text/csv', 'text/html']
            );
        }

        // for model (json/xml)
        if (isset($product_group_item_jsonld)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($product_group_item_jsonld));
            } else {
                $httpBody = $product_group_item_jsonld;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation putProductGroupItemItem
     *
     * Replaces the ProductGroupItem resource.
     *
     * @param  string $id Resource identifier (required)
     * @param  \Vilo\ProductService\Model\ProductGroupItemJsonld $product_group_item_jsonld The updated ProductGroupItem resource (required)
     *
     * @throws \Vilo\ProductService\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead
     */
    public function putProductGroupItemItem($id, $product_group_item_jsonld)
    {
        list($response) = $this->putProductGroupItemItemWithHttpInfo($id, $product_group_item_jsonld);
        return $response;
    }

    /**
     * Operation putProductGroupItemItemWithHttpInfo
     *
     * Replaces the ProductGroupItem resource.
     *
     * @param  string $id Resource identifier (required)
     * @param  \Vilo\ProductService\Model\ProductGroupItemJsonld $product_group_item_jsonld The updated ProductGroupItem resource (required)
     *
     * @throws \Vilo\ProductService\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead, HTTP status code, HTTP response headers (array of strings)
     */
    public function putProductGroupItemItemWithHttpInfo($id, $product_group_item_jsonld)
    {
        $request = $this->putProductGroupItemItemRequest($id, $product_group_item_jsonld);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation putProductGroupItemItemAsync
     *
     * Replaces the ProductGroupItem resource.
     *
     * @param  string $id Resource identifier (required)
     * @param  \Vilo\ProductService\Model\ProductGroupItemJsonld $product_group_item_jsonld The updated ProductGroupItem resource (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function putProductGroupItemItemAsync($id, $product_group_item_jsonld)
    {
        return $this->putProductGroupItemItemAsyncWithHttpInfo($id, $product_group_item_jsonld)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation putProductGroupItemItemAsyncWithHttpInfo
     *
     * Replaces the ProductGroupItem resource.
     *
     * @param  string $id Resource identifier (required)
     * @param  \Vilo\ProductService\Model\ProductGroupItemJsonld $product_group_item_jsonld The updated ProductGroupItem resource (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function putProductGroupItemItemAsyncWithHttpInfo($id, $product_group_item_jsonld)
    {
        $returnType = '\Vilo\ProductService\Model\ProductGroupItemJsonldProductGroupItemRead';
        $request = $this->putProductGroupItemItemRequest($id, $product_group_item_jsonld);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'putProductGroupItemItem'
     *
     * @param  string $id Resource identifier (required)
     * @param  \Vilo\ProductService\Model\ProductGroupItemJsonld $product_group_item_jsonld The updated ProductGroupItem resource (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function putProductGroupItemItemRequest($id, $product_group_item_jsonld)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling putProductGroupItemItem'
            );
        }
        // verify the required parameter 'product_group_item_jsonld' is set
        if ($product_group_item_jsonld === null || (is_array($product_group_item_jsonld) && count($product_group_item_jsonld) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $product_group_item_jsonld when calling putProductGroupItemItem'
            );
        }

        $resourcePath = '/product_group_items/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/ld+json', 'text/csv', 'text/html']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/ld+json', 'text/csv', 'text/html'],
                ['application/ld+json', 'text/csv', 'text/html']
            );
        }

        // for model (json/xml)
        if (isset($product_group_item_jsonld)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($product_group_item_jsonld));
            } else {
                $httpBody = $product_group_item_jsonld;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
