<?php
/**
 * ProductGroupTypeApi
 * PHP version 7.3
 *
 * @category Class
 * @package  Vilo\ProductService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Product Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Vilo\ProductService\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Vilo\ProductService\ApiException;
use Vilo\ProductService\Configuration;
use Vilo\ProductService\HeaderSelector;
use Vilo\ProductService\ObjectSerializer;

/**
 * ProductGroupTypeApi Class Doc Comment
 *
 * @category Class
 * @package  Vilo\ProductService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductGroupTypeApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation deleteProductGroupTypeItem
     *
     * Removes the ProductGroupType resource.
     *
     * @param  string $id Resource identifier (required)
     *
     * @throws \Vilo\ProductService\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteProductGroupTypeItem($id)
    {
        $this->deleteProductGroupTypeItemWithHttpInfo($id);
    }

    /**
     * Operation deleteProductGroupTypeItemWithHttpInfo
     *
     * Removes the ProductGroupType resource.
     *
     * @param  string $id Resource identifier (required)
     *
     * @throws \Vilo\ProductService\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteProductGroupTypeItemWithHttpInfo($id)
    {
        $request = $this->deleteProductGroupTypeItemRequest($id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation deleteProductGroupTypeItemAsync
     *
     * Removes the ProductGroupType resource.
     *
     * @param  string $id Resource identifier (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteProductGroupTypeItemAsync($id)
    {
        return $this->deleteProductGroupTypeItemAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteProductGroupTypeItemAsyncWithHttpInfo
     *
     * Removes the ProductGroupType resource.
     *
     * @param  string $id Resource identifier (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteProductGroupTypeItemAsyncWithHttpInfo($id)
    {
        $returnType = '';
        $request = $this->deleteProductGroupTypeItemRequest($id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteProductGroupTypeItem'
     *
     * @param  string $id Resource identifier (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteProductGroupTypeItemRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling deleteProductGroupTypeItem'
            );
        }

        $resourcePath = '/product_group_types/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getProductGroupTypeCollection
     *
     * Retrieves the collection of ProductGroupType resources.
     *
     * @param  int $page The collection page number (optional, default to 1)
     * @param  int $items_per_page The number of items per page (optional, default to 30)
     * @param  string $key key (optional)
     * @param  string[] $key2 key2 (optional)
     *
     * @throws \Vilo\ProductService\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Vilo\ProductService\Model\InlineResponse2002
     */
    public function getProductGroupTypeCollection($page = 1, $items_per_page = 30, $key = null, $key2 = null)
    {
        list($response) = $this->getProductGroupTypeCollectionWithHttpInfo($page, $items_per_page, $key, $key2);
        return $response;
    }

    /**
     * Operation getProductGroupTypeCollectionWithHttpInfo
     *
     * Retrieves the collection of ProductGroupType resources.
     *
     * @param  int $page The collection page number (optional, default to 1)
     * @param  int $items_per_page The number of items per page (optional, default to 30)
     * @param  string $key (optional)
     * @param  string[] $key2 (optional)
     *
     * @throws \Vilo\ProductService\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Vilo\ProductService\Model\InlineResponse2002, HTTP status code, HTTP response headers (array of strings)
     */
    public function getProductGroupTypeCollectionWithHttpInfo($page = 1, $items_per_page = 30, $key = null, $key2 = null)
    {
        $request = $this->getProductGroupTypeCollectionRequest($page, $items_per_page, $key, $key2);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Vilo\ProductService\Model\InlineResponse2002' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Vilo\ProductService\Model\InlineResponse2002', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Vilo\ProductService\Model\InlineResponse2002';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Vilo\ProductService\Model\InlineResponse2002',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getProductGroupTypeCollectionAsync
     *
     * Retrieves the collection of ProductGroupType resources.
     *
     * @param  int $page The collection page number (optional, default to 1)
     * @param  int $items_per_page The number of items per page (optional, default to 30)
     * @param  string $key (optional)
     * @param  string[] $key2 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProductGroupTypeCollectionAsync($page = 1, $items_per_page = 30, $key = null, $key2 = null)
    {
        return $this->getProductGroupTypeCollectionAsyncWithHttpInfo($page, $items_per_page, $key, $key2)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getProductGroupTypeCollectionAsyncWithHttpInfo
     *
     * Retrieves the collection of ProductGroupType resources.
     *
     * @param  int $page The collection page number (optional, default to 1)
     * @param  int $items_per_page The number of items per page (optional, default to 30)
     * @param  string $key (optional)
     * @param  string[] $key2 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProductGroupTypeCollectionAsyncWithHttpInfo($page = 1, $items_per_page = 30, $key = null, $key2 = null)
    {
        $returnType = '\Vilo\ProductService\Model\InlineResponse2002';
        $request = $this->getProductGroupTypeCollectionRequest($page, $items_per_page, $key, $key2);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getProductGroupTypeCollection'
     *
     * @param  int $page The collection page number (optional, default to 1)
     * @param  int $items_per_page The number of items per page (optional, default to 30)
     * @param  string $key (optional)
     * @param  string[] $key2 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getProductGroupTypeCollectionRequest($page = 1, $items_per_page = 30, $key = null, $key2 = null)
    {
        if ($items_per_page !== null && $items_per_page < 0) {
            throw new \InvalidArgumentException('invalid value for "$items_per_page" when calling ProductGroupTypeApi.getProductGroupTypeCollection, must be bigger than or equal to 0.');
        }


        $resourcePath = '/product_group_types';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if (is_array($page)) {
            $page = ObjectSerializer::serializeCollection($page, 'form', true);
        }
        if ($page !== null) {
            $queryParams['page'] = $page;
        }
        // query params
        if (is_array($items_per_page)) {
            $items_per_page = ObjectSerializer::serializeCollection($items_per_page, 'form', true);
        }
        if ($items_per_page !== null) {
            $queryParams['itemsPerPage'] = $items_per_page;
        }
        // query params
        if (is_array($key)) {
            $key = ObjectSerializer::serializeCollection($key, 'form', true);
        }
        if ($key !== null) {
            $queryParams['key'] = $key;
        }
        // query params
        if ($key2 !== null) {
            if('form' === 'form' && is_array($key2)) {
                foreach($key2 as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['key[]'] = $key2;
            }
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/ld+json', 'text/csv', 'text/html']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/ld+json', 'text/csv', 'text/html'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getProductGroupTypeItem
     *
     * Retrieves a ProductGroupType resource.
     *
     * @param  string $id Resource identifier (required)
     *
     * @throws \Vilo\ProductService\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Vilo\ProductService\Model\ProductGroupTypeJsonld
     */
    public function getProductGroupTypeItem($id)
    {
        list($response) = $this->getProductGroupTypeItemWithHttpInfo($id);
        return $response;
    }

    /**
     * Operation getProductGroupTypeItemWithHttpInfo
     *
     * Retrieves a ProductGroupType resource.
     *
     * @param  string $id Resource identifier (required)
     *
     * @throws \Vilo\ProductService\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Vilo\ProductService\Model\ProductGroupTypeJsonld, HTTP status code, HTTP response headers (array of strings)
     */
    public function getProductGroupTypeItemWithHttpInfo($id)
    {
        $request = $this->getProductGroupTypeItemRequest($id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Vilo\ProductService\Model\ProductGroupTypeJsonld' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Vilo\ProductService\Model\ProductGroupTypeJsonld', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Vilo\ProductService\Model\ProductGroupTypeJsonld';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Vilo\ProductService\Model\ProductGroupTypeJsonld',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getProductGroupTypeItemAsync
     *
     * Retrieves a ProductGroupType resource.
     *
     * @param  string $id Resource identifier (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProductGroupTypeItemAsync($id)
    {
        return $this->getProductGroupTypeItemAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getProductGroupTypeItemAsyncWithHttpInfo
     *
     * Retrieves a ProductGroupType resource.
     *
     * @param  string $id Resource identifier (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProductGroupTypeItemAsyncWithHttpInfo($id)
    {
        $returnType = '\Vilo\ProductService\Model\ProductGroupTypeJsonld';
        $request = $this->getProductGroupTypeItemRequest($id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getProductGroupTypeItem'
     *
     * @param  string $id Resource identifier (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getProductGroupTypeItemRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getProductGroupTypeItem'
            );
        }

        $resourcePath = '/product_group_types/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/ld+json', 'text/csv', 'text/html']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/ld+json', 'text/csv', 'text/html'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation patchProductGroupTypeItem
     *
     * Updates the ProductGroupType resource.
     *
     * @param  string $id Resource identifier (required)
     * @param  \Vilo\ProductService\Model\ProductGroupType $product_group_type The updated ProductGroupType resource (required)
     *
     * @throws \Vilo\ProductService\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Vilo\ProductService\Model\ProductGroupTypeJsonld
     */
    public function patchProductGroupTypeItem($id, $product_group_type)
    {
        list($response) = $this->patchProductGroupTypeItemWithHttpInfo($id, $product_group_type);
        return $response;
    }

    /**
     * Operation patchProductGroupTypeItemWithHttpInfo
     *
     * Updates the ProductGroupType resource.
     *
     * @param  string $id Resource identifier (required)
     * @param  \Vilo\ProductService\Model\ProductGroupType $product_group_type The updated ProductGroupType resource (required)
     *
     * @throws \Vilo\ProductService\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Vilo\ProductService\Model\ProductGroupTypeJsonld, HTTP status code, HTTP response headers (array of strings)
     */
    public function patchProductGroupTypeItemWithHttpInfo($id, $product_group_type)
    {
        $request = $this->patchProductGroupTypeItemRequest($id, $product_group_type);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Vilo\ProductService\Model\ProductGroupTypeJsonld' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Vilo\ProductService\Model\ProductGroupTypeJsonld', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Vilo\ProductService\Model\ProductGroupTypeJsonld';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Vilo\ProductService\Model\ProductGroupTypeJsonld',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation patchProductGroupTypeItemAsync
     *
     * Updates the ProductGroupType resource.
     *
     * @param  string $id Resource identifier (required)
     * @param  \Vilo\ProductService\Model\ProductGroupType $product_group_type The updated ProductGroupType resource (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchProductGroupTypeItemAsync($id, $product_group_type)
    {
        return $this->patchProductGroupTypeItemAsyncWithHttpInfo($id, $product_group_type)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation patchProductGroupTypeItemAsyncWithHttpInfo
     *
     * Updates the ProductGroupType resource.
     *
     * @param  string $id Resource identifier (required)
     * @param  \Vilo\ProductService\Model\ProductGroupType $product_group_type The updated ProductGroupType resource (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchProductGroupTypeItemAsyncWithHttpInfo($id, $product_group_type)
    {
        $returnType = '\Vilo\ProductService\Model\ProductGroupTypeJsonld';
        $request = $this->patchProductGroupTypeItemRequest($id, $product_group_type);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'patchProductGroupTypeItem'
     *
     * @param  string $id Resource identifier (required)
     * @param  \Vilo\ProductService\Model\ProductGroupType $product_group_type The updated ProductGroupType resource (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function patchProductGroupTypeItemRequest($id, $product_group_type)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling patchProductGroupTypeItem'
            );
        }
        // verify the required parameter 'product_group_type' is set
        if ($product_group_type === null || (is_array($product_group_type) && count($product_group_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $product_group_type when calling patchProductGroupTypeItem'
            );
        }

        $resourcePath = '/product_group_types/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/ld+json', 'text/csv', 'text/html']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/ld+json', 'text/csv', 'text/html'],
                ['application/merge-patch+json']
            );
        }

        // for model (json/xml)
        if (isset($product_group_type)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($product_group_type));
            } else {
                $httpBody = $product_group_type;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PATCH',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postProductGroupTypeCollection
     *
     * Creates a ProductGroupType resource.
     *
     * @param  \Vilo\ProductService\Model\ProductGroupTypeJsonld $product_group_type_jsonld The new ProductGroupType resource (required)
     *
     * @throws \Vilo\ProductService\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Vilo\ProductService\Model\ProductGroupTypeJsonld
     */
    public function postProductGroupTypeCollection($product_group_type_jsonld)
    {
        list($response) = $this->postProductGroupTypeCollectionWithHttpInfo($product_group_type_jsonld);
        return $response;
    }

    /**
     * Operation postProductGroupTypeCollectionWithHttpInfo
     *
     * Creates a ProductGroupType resource.
     *
     * @param  \Vilo\ProductService\Model\ProductGroupTypeJsonld $product_group_type_jsonld The new ProductGroupType resource (required)
     *
     * @throws \Vilo\ProductService\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Vilo\ProductService\Model\ProductGroupTypeJsonld, HTTP status code, HTTP response headers (array of strings)
     */
    public function postProductGroupTypeCollectionWithHttpInfo($product_group_type_jsonld)
    {
        $request = $this->postProductGroupTypeCollectionRequest($product_group_type_jsonld);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 201:
                    if ('\Vilo\ProductService\Model\ProductGroupTypeJsonld' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Vilo\ProductService\Model\ProductGroupTypeJsonld', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Vilo\ProductService\Model\ProductGroupTypeJsonld';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Vilo\ProductService\Model\ProductGroupTypeJsonld',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation postProductGroupTypeCollectionAsync
     *
     * Creates a ProductGroupType resource.
     *
     * @param  \Vilo\ProductService\Model\ProductGroupTypeJsonld $product_group_type_jsonld The new ProductGroupType resource (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postProductGroupTypeCollectionAsync($product_group_type_jsonld)
    {
        return $this->postProductGroupTypeCollectionAsyncWithHttpInfo($product_group_type_jsonld)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postProductGroupTypeCollectionAsyncWithHttpInfo
     *
     * Creates a ProductGroupType resource.
     *
     * @param  \Vilo\ProductService\Model\ProductGroupTypeJsonld $product_group_type_jsonld The new ProductGroupType resource (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postProductGroupTypeCollectionAsyncWithHttpInfo($product_group_type_jsonld)
    {
        $returnType = '\Vilo\ProductService\Model\ProductGroupTypeJsonld';
        $request = $this->postProductGroupTypeCollectionRequest($product_group_type_jsonld);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postProductGroupTypeCollection'
     *
     * @param  \Vilo\ProductService\Model\ProductGroupTypeJsonld $product_group_type_jsonld The new ProductGroupType resource (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postProductGroupTypeCollectionRequest($product_group_type_jsonld)
    {
        // verify the required parameter 'product_group_type_jsonld' is set
        if ($product_group_type_jsonld === null || (is_array($product_group_type_jsonld) && count($product_group_type_jsonld) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $product_group_type_jsonld when calling postProductGroupTypeCollection'
            );
        }

        $resourcePath = '/product_group_types';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/ld+json', 'text/csv', 'text/html']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/ld+json', 'text/csv', 'text/html'],
                ['application/ld+json', 'text/csv', 'text/html']
            );
        }

        // for model (json/xml)
        if (isset($product_group_type_jsonld)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($product_group_type_jsonld));
            } else {
                $httpBody = $product_group_type_jsonld;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation putProductGroupTypeItem
     *
     * Replaces the ProductGroupType resource.
     *
     * @param  string $id Resource identifier (required)
     * @param  \Vilo\ProductService\Model\ProductGroupTypeJsonld $product_group_type_jsonld The updated ProductGroupType resource (required)
     *
     * @throws \Vilo\ProductService\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Vilo\ProductService\Model\ProductGroupTypeJsonld
     */
    public function putProductGroupTypeItem($id, $product_group_type_jsonld)
    {
        list($response) = $this->putProductGroupTypeItemWithHttpInfo($id, $product_group_type_jsonld);
        return $response;
    }

    /**
     * Operation putProductGroupTypeItemWithHttpInfo
     *
     * Replaces the ProductGroupType resource.
     *
     * @param  string $id Resource identifier (required)
     * @param  \Vilo\ProductService\Model\ProductGroupTypeJsonld $product_group_type_jsonld The updated ProductGroupType resource (required)
     *
     * @throws \Vilo\ProductService\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Vilo\ProductService\Model\ProductGroupTypeJsonld, HTTP status code, HTTP response headers (array of strings)
     */
    public function putProductGroupTypeItemWithHttpInfo($id, $product_group_type_jsonld)
    {
        $request = $this->putProductGroupTypeItemRequest($id, $product_group_type_jsonld);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Vilo\ProductService\Model\ProductGroupTypeJsonld' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Vilo\ProductService\Model\ProductGroupTypeJsonld', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Vilo\ProductService\Model\ProductGroupTypeJsonld';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Vilo\ProductService\Model\ProductGroupTypeJsonld',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation putProductGroupTypeItemAsync
     *
     * Replaces the ProductGroupType resource.
     *
     * @param  string $id Resource identifier (required)
     * @param  \Vilo\ProductService\Model\ProductGroupTypeJsonld $product_group_type_jsonld The updated ProductGroupType resource (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function putProductGroupTypeItemAsync($id, $product_group_type_jsonld)
    {
        return $this->putProductGroupTypeItemAsyncWithHttpInfo($id, $product_group_type_jsonld)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation putProductGroupTypeItemAsyncWithHttpInfo
     *
     * Replaces the ProductGroupType resource.
     *
     * @param  string $id Resource identifier (required)
     * @param  \Vilo\ProductService\Model\ProductGroupTypeJsonld $product_group_type_jsonld The updated ProductGroupType resource (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function putProductGroupTypeItemAsyncWithHttpInfo($id, $product_group_type_jsonld)
    {
        $returnType = '\Vilo\ProductService\Model\ProductGroupTypeJsonld';
        $request = $this->putProductGroupTypeItemRequest($id, $product_group_type_jsonld);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'putProductGroupTypeItem'
     *
     * @param  string $id Resource identifier (required)
     * @param  \Vilo\ProductService\Model\ProductGroupTypeJsonld $product_group_type_jsonld The updated ProductGroupType resource (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function putProductGroupTypeItemRequest($id, $product_group_type_jsonld)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling putProductGroupTypeItem'
            );
        }
        // verify the required parameter 'product_group_type_jsonld' is set
        if ($product_group_type_jsonld === null || (is_array($product_group_type_jsonld) && count($product_group_type_jsonld) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $product_group_type_jsonld when calling putProductGroupTypeItem'
            );
        }

        $resourcePath = '/product_group_types/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/ld+json', 'text/csv', 'text/html']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/ld+json', 'text/csv', 'text/html'],
                ['application/ld+json', 'text/csv', 'text/html']
            );
        }

        // for model (json/xml)
        if (isset($product_group_type_jsonld)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($product_group_type_jsonld));
            } else {
                $httpBody = $product_group_type_jsonld;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
