<?php
/**
 * ProductGroupItemJsonldTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Vilo\ProductService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Product Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Vilo\ProductService\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ProductGroupItemJsonldTest Class Doc Comment
 *
 * @category    Class
 * @description ProductGroupItemJsonld
 * @package     Vilo\ProductService
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ProductGroupItemJsonldTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ProductGroupItemJsonld"
     */
    public function testProductGroupItemJsonld()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sequence"
     */
    public function testPropertySequence()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fk_product"
     */
    public function testPropertyFkProduct()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fk_product_group"
     */
    public function testPropertyFkProductGroup()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
