<?php
/**
 * AttributeValueApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  Vilo\ProductService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Product Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Vilo\ProductService\Test\Api;

use \Vilo\ProductService\Configuration;
use \Vilo\ProductService\ApiException;
use \Vilo\ProductService\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AttributeValueApiTest Class Doc Comment
 *
 * @category Class
 * @package  Vilo\ProductService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AttributeValueApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for attributableGetAttributeValuesProductSubresource
     *
     * Get All the AttributeValues for the entity Product with {id}.
     *
     */
    public function testAttributableGetAttributeValuesProductSubresource()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for attributeValueAssignProductItem
     *
     * Assign attribute value to a Product entity..
     *
     */
    public function testAttributeValueAssignProductItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for attributeValueCreateProductCollection
     *
     * Add an AttributeValue for an Attribute on the Product entity..
     *
     */
    public function testAttributeValueCreateProductCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for attributeValueGetProductCollection
     *
     * Get the AttributeValues for an Attribute on the Product entity..
     *
     */
    public function testAttributeValueGetProductCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for attributeValueGetProductItem
     *
     * Retrieves a Product resource..
     *
     */
    public function testAttributeValueGetProductItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for attributeValueUnassignProductItem
     *
     * Unassign attribute value from a Product entity..
     *
     */
    public function testAttributeValueUnassignProductItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for attributeValueUpdateProductItem
     *
     * Update an AttributeValue for an Attribute on the Product entity..
     *
     */
    public function testAttributeValueUpdateProductItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
