<?php
/**
 * AttributeSetApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  Vilo\ProductService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Product Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Vilo\ProductService\Test\Api;

use \Vilo\ProductService\Configuration;
use \Vilo\ProductService\ApiException;
use \Vilo\ProductService\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AttributeSetApiTest Class Doc Comment
 *
 * @category Class
 * @package  Vilo\ProductService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AttributeSetApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for productsAttributeSetAssignAttributeAttributeSetItem
     *
     * Assign an Attribute to a Attribute Set for Product.
     *
     */
    public function testProductsAttributeSetAssignAttributeAttributeSetItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsAttributeSetCreate
     *
     * Creates a Attribute Set for Product.
     *
     */
    public function testProductsAttributeSetCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsAttributeSetCreateAttributeSetCollection
     *
     * Retrieves the collection of AttributeSet resources..
     *
     */
    public function testProductsAttributeSetCreateAttributeSetCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsAttributeSetGetItemAttributeSetItem
     *
     * Retrieves a AttributeSet resource..
     *
     */
    public function testProductsAttributeSetGetItemAttributeSetItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
