<?php
/**
 * ProductApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  Vilo\ProductService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Product Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Vilo\ProductService\Test\Api;

use \Vilo\ProductService\Configuration;
use \Vilo\ProductService\ApiException;
use \Vilo\ProductService\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductApiTest Class Doc Comment
 *
 * @category Class
 * @package  Vilo\ProductService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for approveProductItem
     *
     * approving a Product resource.
     *
     */
    public function testApproveProductItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteProductItem
     *
     * Removes the Product resource..
     *
     */
    public function testDeleteProductItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for disapproveProductItem
     *
     * disapproving a Product resource.
     *
     */
    public function testDisapproveProductItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProductCollection
     *
     * Retrieves the collection of Product resources..
     *
     */
    public function testGetProductCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProductItem
     *
     * Retrieves a Product resource..
     *
     */
    public function testGetProductItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchProductItem
     *
     * Updates the Product resource..
     *
     */
    public function testPatchProductItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProductCollection
     *
     * Creates a Product resource..
     *
     */
    public function testPostProductCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for putProductItem
     *
     * Replaces the Product resource..
     *
     */
    public function testPutProductItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
